### ISSUE TITLE
Project specific config file

### ISSUE THREAD

**Issue by carlsmedstad** [cmake-lint/cmake-lint#8]
Hey :wave: 

Is this project still maintained?

If so, I would like to implement project specific config files. I.e. that cmakelint should pick up a config file (`.cmakelintrc`) in the current working directory.

**Comment by shanebishop** [comment]
I would say this project is still maintained, but currently development is not very active. That said, your contribution would be quite welcome! 🙂

**Comment by tkruse** [comment]
I am able to create new releases if necessary. However I am not using cmake-lint myself, nor do I know how much it is being used in the wild, apart from pypi download statistics.

The script already picks up cmakelintrc from some global locations, adding the ability to also pick this up in the project is probably useful, so I would be happy to merge that.

**Comment by tkruse** [comment]
fixed in 1.4.2 using #9
